<?php
require_once 'common/header.php';
require_once 'common/sidebar.php'; 


// ডাটাবেস থেকে অ্যাক্টিভ ব্যানার আনা
$slides_stmt = $pdo->query("SELECT image, link_url FROM slideshow WHERE is_active = 1 ORDER BY sort_order ASC");
$slides_data = $slides_stmt->fetchAll();


// ডাটাবেস থেকে ডেটা আনা
// শপ বাই ক্যাটাগরি (16টি দেখানো হবে)
$stmt_cat = $pdo->query("SELECT id, name, image FROM categories ORDER BY name ASC LIMIT 16");
$categories = $stmt_cat->fetchAll();

// ট্রেন্ডিং প্রোডাক্ট (নতুন যোগ করা ৪টি প্রোডাক্ট)
$stmt_trending = $pdo->query("SELECT id, name, image FROM products ORDER BY created_at DESC LIMIT 4");
$trending_products = $stmt_trending->fetchAll();

// ফিচারড প্রোডাক্ট (পুরোনো ডিজাইন অনুযায়ী)
$stmt_featured = $pdo->query("SELECT id, name, price, image FROM products ORDER BY RAND() LIMIT 8");
$featured_products = $stmt_featured->fetchAll();
?>



<!-- সাইডবার (আগের মতোই থাকবে) -->
<?php require_once 'common/sidebar.php'; ?>



<main class="p-4 bg-white">
    <!-- প্রমোশনাল ব্যানার -->

    <!-- Slideshow Section - DYNAMIC -->
    <?php if (!empty($slides_data)): ?>
    <section class="mb-8">
        <div id="slideshow-container" class="relative w-full max-w-4xl mx-auto rounded-lg overflow-hidden shadow-lg group">
            <!-- Slides Wrapper -->
            <div id="slideshow-wrapper" class="flex transition-transform duration-500 ease-in-out">
                <?php foreach ($slides_data as $slide): ?>
                <div class="w-full flex-shrink-0">
                    <a href="<?= htmlspecialchars($slide['link_url'] ?: '#') ?>">
                        <img src="uploads/<?= htmlspecialchars($slide['image']) ?>" alt="Slideshow Image" class="w-full aspect-video object-cover">
                    </a>
                </div>
                <?php endforeach; ?>
            </div>

            <!-- Controls -->
            <button id="prev-btn" class="absolute hidden group-hover:block top-1/2 left-0 transform -translate-y-1/2 bg-black bg-opacity-40 text-white rounded-full h-8 w-8 flex items-center justify-center z-10 hover:bg-opacity-60">
                <i class="fas fa-chevron-left"></i>
            </button>
            <button id="next-btn" class="absolute hidden group-hover:block top-1/2 right-0 transform -translate-y-1/2 bg-black bg-opacity-40 text-white rounded-full h-8 w-8 flex items-center justify-center z-10 hover:bg-opacity-60">
                <i class="fas fa-chevron-right"></i>
            </button>

            <!-- Indicators -->
            <div id="indicators-container" class="absolute bottom-4 left-1/2 transform -translate-x-1/2 flex space-x-2 z-10">
                <!-- Indicators are now generated by JavaScript based on the dynamic slides -->
            </div>
        </div>
    </section>
    <?php endif; ?>
    <!-- End Slideshow Section -->

    <!-- সার্চ বার -->
    <section class="mb-6">
        <form action="search.php" method="GET" class="relative">
            <input type="text" name="q" placeholder="Search for products..." class="w-full py-3 pl-10 pr-4 text-gray-700 bg-gray-100 border border-gray-200 rounded-3xl focus:outline-none focus:ring-2 focus:ring-indigo-400" required>
            <span class="absolute top-1/2 left-3 transform -translate-y-1/2 text-gray-400">
                <i class="fas fa-search"></i>
            </span>
        </form>
    </section>

    <!-- শপ বাই ক্যাটাগরি -->
    <section class="mb-8">
        <div class="flex justify-between items-center mb-4">
            <h2 class="text-lg font-bold text-gray-800">Shop by Category</h2>
            <a href="" class="text-sm font-medium text-indigo-600">View All</a>
        </div>
        <div class="flex space-x-4 overflow-hidden pb-2">
            <?php foreach ($categories as $category): ?>
            <a href="product.php?cat_id=<?= $category['id'] ?>" class="flex-shrink-0 text-center space-y-2 w-20">
                <div class="w-16 h-16 mx-auto bg-white rounded-full shadow-md flex items-center justify-center p-1">
                    <img src="uploads/<?= htmlspecialchars($category['image'] ?: 'category_placeholder.png') ?>" alt="<?= htmlspecialchars($category['name']) ?>" class="w-full h-full object-contain rounded-full">
                </div>
                <span class="text-xs font-medium text-gray-600 block truncate"><?= htmlspecialchars($category['name']) ?></span>
            </a>
            <?php endforeach; ?>
        </div>
    </section>

    <!-- ট্রেন্ডিং নাও -->
    <section class="mb-8">
        <div class="flex justify-between items-center mb-4">
            <h2 class="text-lg font-bold text-gray-800 flex items-center"><i class="fas fa-fire-alt text-red-500 mr-2"></i>Trending Now</h2>
            <a href="#" class="text-sm font-medium text-indigo-600">View All</a>
        </div>
        <div class="grid grid-cols-2 gap-4">
            <?php foreach ($trending_products as $product): ?>
            <a href="product_detail.php?id=<?= $product['id'] ?>" class="block bg-white rounded-lg shadow-sm p-3 border border-gray-100">
                <img src="uploads/<?= htmlspecialchars($product['image'] ?: 'product_placeholder.jpg') ?>" alt="<?= htmlspecialchars($product['name']) ?>" class="w-full h-28 object-contain mb-2 rounded-md">
                <h3 class="text-sm font-medium text-gray-700 truncate"><?= htmlspecialchars($product['name']) ?></h3>
            </a>
            <?php endforeach; ?>
        </div>
    </section>

    <!-- ফিচারড প্রোডাক্টস (আপনার পুরোনো ডিজাইন অনুযায়ী) -->
    <section>
        <div class="flex justify-between items-center mb-4">
            <h2 class="text-lg font-bold text-gray-800">Featured Products</h2>
            <a href="#" class="text-sm font-medium text-indigo-600">View All</a>
        </div>
        <div class="grid grid-cols-2 gap-4">
            <?php foreach ($featured_products as $product): ?>
            <div class="bg-white rounded-lg shadow-md overflow-hidden transform hover:scale-105 transition-transform duration-300">
                <a href="product_detail.php?id=<?= $product['id'] ?>" class="block">
                    <img src="uploads/<?= htmlspecialchars($product['image'] ?: 'product_placeholder.jpg') ?>" alt="<?= htmlspecialchars($product['name']) ?>" class="w-full h-32 object-cover">
                    <div class="p-3">
                        <h3 class="text-sm font-semibold text-gray-800 truncate"><?= htmlspecialchars($product['name']) ?></h3>
                        <p class="text-md font-bold text-indigo-600 mt-1"><?= format_price($product['price']) ?></p>
                    </div>
                </a>
                <div class="px-3 pb-3">
                     <button onclick="addToCart(<?= $product['id'] ?>)" class="w-full bg-indigo-500 text-white text-xs font-bold py-2 rounded-md hover:bg-indigo-600 transition-colors">
                        Add to Cart
                    </button>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </section>
</main>

<!-- বটম নেভিগেশন (হোম আইকন অ্যাক্টিভ) -->
<nav class="fixed bottom-0 left-0 right-0 bg-white shadow-[0_-1px_5px_rgba(0,0,0,0.1)] z-40 flex justify-around">
    <a href="index.php" class="flex-1 flex flex-col items-center justify-center py-2 text-indigo-600">
        <i class="fas fa-home text-xl"></i><span class="text-xs font-medium">Home</span>
    </a>
    <a href="cart.php" class="flex-1 flex flex-col items-center justify-center py-2 text-gray-500 hover:text-indigo-600">
        <i class="fas fa-shopping-cart text-xl"></i><span class="text-xs font-medium">Cart</span>
    </a>
    <a href="order.php" class="flex-1 flex flex-col items-center justify-center py-2 text-gray-500 hover:text-indigo-600">
         <i class="fas fa-receipt text-xl"></i><span class="text-xs font-medium">Orders</span>
    </a>
    <a href="profile.php" class="flex-1 flex flex-col items-center justify-center py-2 text-gray-500 hover:text-indigo-600">
        <i class="fas fa-user-circle text-xl"></i><span class="text-xs font-medium">Profile</span>
    </a>
</nav>


<script>


    // --- Slideshow JavaScript ---
    document.addEventListener('DOMContentLoaded', () => {
        const slideshowContainer = document.getElementById('slideshow-container');
        if (slideshowContainer) { // Only run if the slideshow exists on the page
            const wrapper = document.getElementById('slideshow-wrapper');
            const slides = Array.from(wrapper.children);
            if (slides.length === 0) return; // Don't initialize if there are no slides

            const nextBtn = document.getElementById('next-btn');
            const prevBtn = document.getElementById('prev-btn');
            const indicatorsContainer = document.getElementById('indicators-container');
            let currentIndex = 0;
            let slideInterval;

            // Create indicators
            slides.forEach((_, index) => {
                const button = document.createElement('button');
                button.classList.add('w-2', 'h-2', 'rounded-full', 'bg-white', 'bg-opacity-50', 'hover:bg-opacity-100', 'transition-opacity');
                button.addEventListener('click', () => {
                    goToSlide(index);
                    resetInterval();
                });
                indicatorsContainer.appendChild(button);
            });

            const indicators = Array.from(indicatorsContainer.children);

            function goToSlide(index) {
                if (index < 0) index = slides.length - 1;
                if (index >= slides.length) index = 0;
                wrapper.style.transform = `translateX(-${index * 100}%)`;
                currentIndex = index;
                updateIndicators();
            }

            function updateIndicators() {
                indicators.forEach((indicator, idx) => {
                    indicator.classList.toggle('bg-opacity-100', idx === currentIndex);
                    indicator.classList.toggle('bg-opacity-50', idx !== currentIndex);
                });
            }

            function resetInterval() {
                clearInterval(slideInterval);
                slideInterval = setInterval(() => goToSlide(currentIndex + 1), 5000);
            }

            prevBtn.addEventListener('click', () => { goToSlide(currentIndex - 1); resetInterval(); });
            nextBtn.addEventListener('click', () => { goToSlide(currentIndex + 1); resetInterval(); });

            goToSlide(0);
            resetInterval();
        }
    });

    
    // কার্ট ফাংশনালিটির জন্য জাভাস্ক্রিপ্ট (অপরিবর্তিত)
    async function addToCart(productId) {
        showLoader();
        const formData = new FormData();
        formData.append('action', 'add');
        formData.append('product_id', productId);
        formData.append('quantity', 1);
        formData.append('ajax', '1');

        try {
            const response = await fetch('cart.php', { method: 'POST', body: formData });
            const result = await response.json();
            if (result.status === 'success') {
                showAlert('Product added to cart!');
                // Update cart count in header
                const cartCountEl = document.getElementById('cart-count');
                if (cartCountEl && result.cart_count !== undefined) {
                    cartCountEl.textContent = result.cart_count;
                }
            } else {
                showAlert(result.message || 'Failed to add to cart.', true);
                location.reload();
            }
        } catch (error) {
            showAlert('An error occurred.', true);
            location.reload();
        } finally {
            hideLoader();
        }
    }
</script>

<?php 
// config.php এবং bottom.php এখানে লোড করা হচ্ছে
require_once 'common/config.php';
require_once 'common/bottom.php'; 
?>